spring:
  application:
    name: biz-product

server:
  port: 8083

dubbo:
  protocol:
    port: 20003
    threads: 20
    queues: 0
  registry:
    address: zookeeper://localhost:2181
  qos:
    enable: true
    port: 22223
  provider:
    timeout: 5000
    retries: 0
  consumer:
    check: false

sentinel:
  enable: true
  clientPort: 8703
  dashboardUrl: localhost:9999
